backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "public/site-config.json"
        label: "Site Configuration"
        name: "site-config"
        fields:
          - { label: "Site Title", name: "title", widget: "string", required: true }
          - { label: "Site Description", name: "description", widget: "text", required: false }
          - { label: "Background Color", name: "color-background", widget: "string", required: false }
          - { label: "Surface Color", name: "color-surface", widget: "string", required: false }
          - { label: "Text Color", name: "color-text", widget: "string", required: false }
          - { label: "Accent Color", name: "color-accent", widget: "string", required: false }
          
  - name: "pdfs"
    label: "PDFs"
    folder: "content/pdfs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Artists", name: "artists", widget: "list" } 
      - { label: "Instruments", name: "instruments", widget: "list" } 
      - { label: "Genres", name: "genres", widget: "list" } 
      - { label: "Description", name: "description", widget: "text" }
      - { label: "PDF File", name: "file", widget: "file", media_library: { config: { multiple: false } } }
      - { label: "Tags", name: "tags", widget: "list" } 