backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    file: "public/site-config.json"
    format: "json"
    fields:
      - { label: "Site Title", name: "title", widget: "string", required: true }
      - { label: "Site Description", name: "description", widget: "text", required: false }
      - label: "Colors"
        name: "colors"
        widget: "object"
        fields:
          - { label: "Background Color", name: "background", widget: "string", required: true }
          - { label: "Surface Color", name: "surface", widget: "string", required: true }
          - { label: "Text Color", name: "text", widget: "string", required: true }
          - { label: "Accent Color", name: "accent", widget: "string", required: true }

  - name: "pdfs"
    label: "PDFs"
    folder: "content/pdfs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Artists", name: "artists", widget: "list" } 
      - { label: "Instruments", name: "instruments", widget: "list" } 
      - { label: "Genres", name: "genres", widget: "list" } 
      - { label: "Description", name: "description", widget: "text" }
      - { label: "PDF File", name: "file", widget: "file", media_library: { config: { multiple: false } } }
      - { label: "Tags", name: "tags", widget: "list" } 